services:
  rabbitmq:
    image: rabbitmq:3.9-management
    platform: linux/amd64
    container_name: rabbitmq-cnpj
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq-data:
    name: rabbitmq-data-cnpj 